moveit_simple_controller_manager:
  controller_names:
    - arm_controller
  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - base_to_waist_joint
      - shoulder_joint
      - elbow_joint
      - wrist_roll_joint
